apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: warehouse-management-namespace
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

