apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice-deployment
  namespace: warehouse-management-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-microservice
  template:
    metadata:
      labels:
        app: product-microservice
    spec:
      containers:
      - name: product-microservice
        image: warehousemanagement.azurecr.io/productmicroservice:latest
        env:
        - name: HOST
          value: "product-db"
        - name: USERNAME
          value: "postgres"
        - name: PASSWORD
          value: "admin"
        - name: DATABASE
          value: "ProductsDb"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: RABBITMQ_HOSTNAME
          value: "rabbitmqq"
        - name: RABBITMQ_USERNAME
          value: "user"
        - name: RABBITMQ_PASSWORD
          value: "admin"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_ProductExchange
          value: "product.exchange"
        ports:
        - containerPort: 8080
