apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgres-deployment
  namespace: warehouse-management-namespace
  labels:
    app: product-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-postgres
  template:
    metadata:
      labels:
        app: product-postgres
    spec:
      containers:
      - name: product-postgres
        image: warehousemanagement.azurecr.io/product-postgres
        env:
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: ProductsDb
        - name: POSTGRES_USER
          value: postgres 
        ports:
        - containerPort: 5432
