services:
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    environment:
        - HOST=db
        - USERNAME=postgres
        - PASSWORD=admin
        - DATABASE=ProductsDb
        - ASPNETCORE_ENVIRONMENT=Development
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    ports:
        - 5049:8080
        - 7112:8081
    networks:
        - product-postgres-network
        - warehouse-network

  db:
    image: postgres:latest
    ports:
        - 5432:5432
    volumes:
        - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
        - product-postgres-network
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=ProductsDb

  redis:
    image: redis:latest
    ports:
        - 6379:6379
    networks:
        - warehouse-network
    volumes:
        - c:/Users/lapkomputer/source/repos/WarehouseManagement.Microservices/redis-cache:/data

  apigateway:
    image: apigateway
    build:
        context: ../WarehouseApiGateway
        dockerfile: WarehouseApiGateway/Dockerfile
    ports:
        - 5000:8080
    networks:
        - warehouse-network

networks:
    product-postgres-network:
        driver: "bridge"
    warehouse-network:
        driver: "bridge"


