apiVersion: apps/v1
kind: Deployment
metadata:
    name: warehouse-management-deployment
    labels: 
        app: product-microservice
    spec:
        replicas: 1
        selector:
            matchLabels:
                app: product-microservice
    template:
        metadata:
            labels:
                app:product-microservice
        spec:
            containers:
                - product-microservice